
package byui.cit260.sudoku.frames;

import byui.cit260.sudoku.controls.GameDifficultyControl;
/**
 *
 * @author Keith
 */
public class GameDifficultyFrame extends javax.swing.JFrame {

    GameDifficultyControl difficulty = new GameDifficultyControl();
    public int diff;
    /**
     * Creates new form GameDifficultyFrame
     */
    public GameDifficultyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblDifficultyLevel = new javax.swing.JLabel();
        jbtnEasy = new javax.swing.JButton();
        jbtnMedium = new javax.swing.JButton();
        jbtnHard = new javax.swing.JButton();
        jbtnExtreme = new javax.swing.JButton();
        jbtnSurpriseMe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("difficultyFrame"); // NOI18N

        jlblDifficultyLevel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlblDifficultyLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDifficultyLevel.setText("Select your difficulty level");

        jbtnEasy.setText("Easy");
        jbtnEasy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEasyMouseClicked(evt);
            }
        });

        jbtnMedium.setText("Medium");
        jbtnMedium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnMediumMouseClicked(evt);
            }
        });

        jbtnHard.setText("Hard");
        jbtnHard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnHardMouseClicked(evt);
            }
        });

        jbtnExtreme.setText("Extreme");
        jbtnExtreme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExtremeMouseClicked(evt);
            }
        });

        jbtnSurpriseMe.setText("Surprise Me");
        jbtnSurpriseMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSurpriseMeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jbtnEasy)
                .addGap(82, 82, 82)
                .addComponent(jbtnMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnHard)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jbtnExtreme)
                        .addGap(79, 79, 79)
                        .addComponent(jbtnSurpriseMe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEasy)
                    .addComponent(jbtnMedium)
                    .addComponent(jbtnHard))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnExtreme)
                    .addComponent(jbtnSurpriseMe))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEasyMouseClicked
        // TODO add your handling code here:
        diff = difficulty.getGameDifficulty("E");
        setVisible(false);
    }//GEN-LAST:event_jbtnEasyMouseClicked

    private void jbtnMediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMediumMouseClicked
        // TODO add your handling code here:
        diff = difficulty.getGameDifficulty("M");
        setVisible(false);
    }//GEN-LAST:event_jbtnMediumMouseClicked

    private void jbtnHardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHardMouseClicked
        // TODO add your handling code here:
        diff = difficulty.getGameDifficulty("H");
        dispose();
    }//GEN-LAST:event_jbtnHardMouseClicked

    private void jbtnExtremeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExtremeMouseClicked
        // TODO add your handling code here:
        diff = difficulty.getGameDifficulty("X");
        dispose();
    }//GEN-LAST:event_jbtnExtremeMouseClicked

    private void jbtnSurpriseMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSurpriseMeMouseClicked
        // TODO add your handling code here:
        diff = difficulty.getGameDifficulty("");
        dispose();
    }//GEN-LAST:event_jbtnSurpriseMeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDifficultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDifficultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDifficultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDifficultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameDifficultyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEasy;
    private javax.swing.JButton jbtnExtreme;
    private javax.swing.JButton jbtnHard;
    private javax.swing.JButton jbtnMedium;
    private javax.swing.JButton jbtnSurpriseMe;
    private javax.swing.JLabel jlblDifficultyLevel;
    // End of variables declaration//GEN-END:variables
}
