package byui.cit260.sudoku.frames;

import byui.cit260.sudoku.controls.HelpMenuControl;
import byui.cit260.sudoku.enums.HelpType;

/**
 *
 * @author Keith Higbee, Jae Dillree, Josiah Hendricks, Jessie Gomez, Daniel Allen
 */

public class HelpFrame extends javax.swing.JFrame {
    HelpMenuControl helpCommands = new HelpMenuControl();
    
    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        setLocationRelativeTo(null); //centers the JFrame on the screen
    }

    public HelpMenuControl getHelpCommands() {
        return helpCommands;
    }
    
    private void displayHelpText(HelpType command) {
        String helpText = helpCommands.getHelpText(command);
        jtHelp.setText(helpText);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jLblSudokuHelp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHelp = new javax.swing.JTextArea();
        jpMenuItems = new javax.swing.JPanel();
        jBtnBoardHelp = new javax.swing.JButton();
        jBtnNumbersHelp = new javax.swing.JButton();
        jBtnPlayerHelp = new javax.swing.JButton();
        jBtnStatisticsHelp = new javax.swing.JButton();
        jBtnEndGameHelp = new javax.swing.JButton();
        jBtnExitHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Help");
        setPreferredSize(new java.awt.Dimension(900, 675));

        jpBody.setBackground(new java.awt.Color(204, 204, 204));
        jpBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpTitle.setBackground(new java.awt.Color(204, 204, 204));

        jLblSudokuHelp.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLblSudokuHelp.setText("Sudoku Help");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblSudokuHelp)
                .addGap(302, 302, 302))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLblSudokuHelp)
                .addGap(66, 66, 66))
        );

        jtHelp.setEditable(false);
        jtHelp.setColumns(20);
        jtHelp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtHelp.setLineWrap(true);
        jtHelp.setRows(5);
        jtHelp.setText("This is the help section of Sudoku.  To find out more about specific functions of the game, select your desired option on the left.");
        jtHelp.setWrapStyleWord(true);
        jtHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtHelp.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jtHelp);

        jBtnBoardHelp.setText("Board Help");
        jBtnBoardHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBoardHelpActionPerformed(evt);
            }
        });

        jBtnNumbersHelp.setText("Numbers Help");
        jBtnNumbersHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumbersHelpActionPerformed(evt);
            }
        });

        jBtnPlayerHelp.setText("Player Help");
        jBtnPlayerHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayerHelpActionPerformed(evt);
            }
        });

        jBtnStatisticsHelp.setText("Statistics Help");
        jBtnStatisticsHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStatisticsHelpActionPerformed(evt);
            }
        });

        jBtnEndGameHelp.setText("End Game Help");
        jBtnEndGameHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEndGameHelpActionPerformed(evt);
            }
        });

        jBtnExitHelp.setText("Exit Help");
        jBtnExitHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnExitHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuItemsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPlayerHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnEndGameHelp, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jpMenuItemsLayout.createSequentialGroup()
                        .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnBoardHelp)
                            .addComponent(jBtnNumbersHelp)
                            .addComponent(jBtnStatisticsHelp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpMenuItemsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnBoardHelp, jBtnEndGameHelp, jBtnNumbersHelp, jBtnPlayerHelp, jBtnStatisticsHelp});

        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jBtnBoardHelp)
                .addGap(18, 18, 18)
                .addComponent(jBtnNumbersHelp)
                .addGap(18, 18, 18)
                .addComponent(jBtnPlayerHelp)
                .addGap(18, 18, 18)
                .addComponent(jBtnStatisticsHelp)
                .addGap(18, 18, 18)
                .addComponent(jBtnEndGameHelp)
                .addGap(18, 18, 18)
                .addComponent(jBtnExitHelp)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBoardHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBoardHelpActionPerformed
        displayHelpText(HelpType.BOARD);
    }//GEN-LAST:event_jBtnBoardHelpActionPerformed

    private void jBtnNumbersHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumbersHelpActionPerformed
        displayHelpText(HelpType.NUMBERS);
    }//GEN-LAST:event_jBtnNumbersHelpActionPerformed

    private void jBtnPlayerHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayerHelpActionPerformed
        displayHelpText(HelpType.PLAYER);
    }//GEN-LAST:event_jBtnPlayerHelpActionPerformed

    private void jBtnStatisticsHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStatisticsHelpActionPerformed
        displayHelpText(HelpType.STATISTICS);
    }//GEN-LAST:event_jBtnStatisticsHelpActionPerformed

    private void jBtnEndGameHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEndGameHelpActionPerformed
        displayHelpText(HelpType.ENDGAME);
    }//GEN-LAST:event_jBtnEndGameHelpActionPerformed

    private void jBtnExitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitHelpActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnExitHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="cjpBodyd" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBoardHelp;
    private javax.swing.JButton jBtnEndGameHelp;
    private javax.swing.JButton jBtnExitHelp;
    private javax.swing.JButton jBtnNumbersHelp;
    private javax.swing.JButton jBtnPlayerHelp;
    private javax.swing.JButton jBtnStatisticsHelp;
    private javax.swing.JLabel jLblSudokuHelp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JTextArea jtHelp;
    // End of variables declaration//GEN-END:variables
}
