package byui.cit260.sudoku.frames;

import byui.cit260.sudoku.controls.MainMenuControl;
import byui.cit260.sudoku.models.Sudoku;
/**
 *
 * @author Keith Higbee, Jae Dillree, Josiah Hendricks, Jessie Gomez, Daniel Allen
 */

public class MainFrame extends javax.swing.JFrame {
    private MainMenuControl mainCommands = new MainMenuControl();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null); //centers the JFrame on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jpTitleLabel = new javax.swing.JLabel();
        jpMenuItems = new javax.swing.JPanel();
        jpBtnNewGame = new javax.swing.JButton();
        jpBtnPlayerOptions = new javax.swing.JButton();
        jpBtnGamePreferences = new javax.swing.JButton();
        jpBtnHelp = new javax.swing.JButton();
        jpBtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtWelcome = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");

        jpBody.setBackground(new java.awt.Color(204, 204, 204));
        jpBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpTitle.setBackground(new java.awt.Color(204, 204, 204));

        jpTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jpTitleLabel.setText("Sudoku");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpTitleLabel)
                .addGap(353, 353, 353))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpTitleLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jpMenuItems.setBackground(new java.awt.Color(204, 255, 204));
        jpMenuItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpBtnNewGame.setText("New Game");
        jpBtnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBtnNewGameActionPerformed(evt);
            }
        });

        jpBtnPlayerOptions.setText("Player Options");
        jpBtnPlayerOptions.setToolTipText("");
        jpBtnPlayerOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBtnPlayerOptionsActionPerformed(evt);
            }
        });

        jpBtnGamePreferences.setText("Preferences");
        jpBtnGamePreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBtnGamePreferencesActionPerformed(evt);
            }
        });

        jpBtnHelp.setText("Help");
        jpBtnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBtnHelpActionPerformed(evt);
            }
        });

        jpBtnExit.setText("Exit");
        jpBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpBtnPlayerOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBtnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBtnGamePreferences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBtnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jpBtnNewGame)
                .addGap(27, 27, 27)
                .addComponent(jpBtnPlayerOptions)
                .addGap(28, 28, 28)
                .addComponent(jpBtnGamePreferences)
                .addGap(30, 30, 30)
                .addComponent(jpBtnHelp)
                .addGap(27, 27, 27)
                .addComponent(jpBtnExit)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jtWelcome.setEditable(false);
        jtWelcome.setColumns(20);
        jtWelcome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtWelcome.setLineWrap(true);
        jtWelcome.setRows(5);
        jtWelcome.setText("Welcome to the game of Sudoku!\n\nThe object of Sudoku is to place the digits of 1 to 9 in each empty cell. Each row, column, and 3 x 3 box must contain only one of each of the 9 digits.\n\nGood Luck!!!  ");
        jtWelcome.setWrapStyleWord(true);
        jtWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtWelcome.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jtWelcome);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpBtnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBtnNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBtnNewGameActionPerformed

    private void jpBtnPlayerOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBtnPlayerOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBtnPlayerOptionsActionPerformed

    private void jpBtnGamePreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBtnGamePreferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBtnGamePreferencesActionPerformed

    private void jpBtnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBtnHelpActionPerformed
        HelpFrame helpFrame = new HelpFrame();
        helpFrame.setVisible(true);
    }//GEN-LAST:event_jpBtnHelpActionPerformed

    private void jpBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jpBtnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBody;
    private javax.swing.JButton jpBtnExit;
    private javax.swing.JButton jpBtnGamePreferences;
    private javax.swing.JButton jpBtnHelp;
    private javax.swing.JButton jpBtnNewGame;
    private javax.swing.JButton jpBtnPlayerOptions;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JLabel jpTitleLabel;
    private javax.swing.JTextArea jtWelcome;
    // End of variables declaration//GEN-END:variables
}
