/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.sudoku.frames;

import byui.cit260.sudoku.controls.GameDifficultyControl;
import byui.cit260.sudoku.models.Grid;
//import java.util.*;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author Keith
 */
public class SudokuFrame extends javax.swing.JFrame {
    
    //private int[][] newgame;
    Integer[][] gameArray = new Integer[9][9]; //variable used to fill the jTable

    /**
     * Creates new form SudokuFrame
     */
    public SudokuFrame() {
        Grid newGrid = new Grid();
        //GameDifficultyControl gameDifficulty = new GameDifficultyControl();
        //int d = gameDifficulty.getDifficultyLevel();
        newGrid.newGame();
        gameArray = newGrid.getGame();
        
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGridHolder = new javax.swing.JPanel();
        jpGrid = new javax.swing.JPanel();
        jpSudokuTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpTableHolder = new javax.swing.JPanel();
        jtSudokuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jpGridHolder.setLayout(new java.awt.GridLayout(1, 0));

        jpGrid.setBackground(new java.awt.Color(204, 204, 204));
        jpGrid.setMaximumSize(new java.awt.Dimension(900, 625));
        jpGrid.setPreferredSize(new java.awt.Dimension(900, 625));

        jpSudokuTitle.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel1.setText("Sudoku Game");

        javax.swing.GroupLayout jpSudokuTitleLayout = new javax.swing.GroupLayout(jpSudokuTitle);
        jpSudokuTitle.setLayout(jpSudokuTitleLayout);
        jpSudokuTitleLayout.setHorizontalGroup(
            jpSudokuTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSudokuTitleLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jpSudokuTitleLayout.setVerticalGroup(
            jpSudokuTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSudokuTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpTableHolder.setBackground(new java.awt.Color(204, 204, 204));

        jtSudokuTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtSudokuTable.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtSudokuTable.setModel(new javax.swing.table.DefaultTableModel(
            gameArray
            ,
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        jtSudokuTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtSudokuTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtSudokuTable.setFillsViewportHeight(true);
        jtSudokuTable.setRowHeight(48);
        jtSudokuTable.setRowSelectionAllowed(false);
        jtSudokuTable.getTableHeader().setReorderingAllowed(false);

        javax.swing.GroupLayout jpTableHolderLayout = new javax.swing.GroupLayout(jpTableHolder);
        jpTableHolder.setLayout(jpTableHolderLayout);
        jpTableHolderLayout.setHorizontalGroup(
            jpTableHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTableHolderLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jtSudokuTable, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jpTableHolderLayout.setVerticalGroup(
            jpTableHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTableHolderLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jtSudokuTable, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtSudokuTable.getAccessibleContext().setAccessibleParent(jpTableHolder);

        javax.swing.GroupLayout jpGridLayout = new javax.swing.GroupLayout(jpGrid);
        jpGrid.setLayout(jpGridLayout);
        jpGridLayout.setHorizontalGroup(
            jpGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGridLayout.createSequentialGroup()
                        .addComponent(jpTableHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpSudokuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpGridLayout.setVerticalGroup(
            jpGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSudokuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpTableHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpGridHolder.add(jpGrid);

        getContentPane().add(jpGridHolder);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuFrame().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpGrid;
    private javax.swing.JPanel jpGridHolder;
    private javax.swing.JPanel jpSudokuTitle;
    private javax.swing.JPanel jpTableHolder;
    private javax.swing.JTable jtSudokuTable;
    // End of variables declaration//GEN-END:variables
}
